/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AcceptDialog: typeof import('./resources/js/components/alerts/AcceptDialog.vue')['default']
    AlertDangerDialog: typeof import('./resources/js/components/alerts/AlertDangerDialog.vue')['default']
    CalendarEventDialog: typeof import('./resources/js/components/dialog/CalendarEventDialog.vue')['default']
    CardStatisticsHorizontal: typeof import('./resources/js/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./resources/js/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./resources/js/@core/components/cards/CardStatisticsWithImages.vue')['default']
    DepartmentDialog: typeof import('./resources/js/components/dialog/DepartmentDialog.vue')['default']
    ErrorHeader: typeof import('./resources/js/components/ErrorHeader.vue')['default']
    MoreBtn: typeof import('./resources/js/@core/components/MoreBtn.vue')['default']
    PositionDialog: typeof import('./resources/js/components/dialog/PositionDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./resources/js/components/toaster/Snackbar.vue')['default']
    ThemeSwitcher: typeof import('./resources/js/@core/components/ThemeSwitcher.vue')['default']
    UpgradeToPro: typeof import('./resources/js/components/UpgradeToPro.vue')['default']
    UserDialog: typeof import('./resources/js/components/dialog/UserDialog.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
